// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiJtHmhu73gFJYxsZPgkCHLlbqCIAvxY',
    appId: '1:70486958869:web:3792bbcf89bb4b2e063f1c',
    messagingSenderId: '70486958869',
    projectId: 'for-firebase-aa26d',
    authDomain: 'for-firebase-aa26d.firebaseapp.com',
    storageBucket: 'for-firebase-aa26d.appspot.com',
    measurementId: 'G-LQN1L5DD5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIUxNOwvrZQ2BH7BX8CyqntaSiq8DYIg0',
    appId: '1:70486958869:android:23f7e00a730474c8063f1c',
    messagingSenderId: '70486958869',
    projectId: 'for-firebase-aa26d',
    storageBucket: 'for-firebase-aa26d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kBitYj0uy5mEftcHlfwVGce4daZKKkg',
    appId: '1:70486958869:ios:13937594d572cee3063f1c',
    messagingSenderId: '70486958869',
    projectId: 'for-firebase-aa26d',
    storageBucket: 'for-firebase-aa26d.appspot.com',
    iosClientId: '70486958869-eolsljjpna6aecmgl295armf83sig3ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishEcommersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kBitYj0uy5mEftcHlfwVGce4daZKKkg',
    appId: '1:70486958869:ios:fa1e9eb3fed35075063f1c',
    messagingSenderId: '70486958869',
    projectId: 'for-firebase-aa26d',
    storageBucket: 'for-firebase-aa26d.appspot.com',
    iosClientId: '70486958869-9h04auvvlr85ej3l6shopr7l0lr5sc4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishEcommersApp.RunnerTests',
  );
}
